### ISSUE TITLE
wrong apostrophe in README.md

### ISSUE THREAD

**Issue by keithbriggs** [m4r35n357/ODE-Playground#1]
it's history

**Comment by m4r35n357** [comment]
Fixed locally, will be uploaded when I have something more substantial to commit, or by next Friday if not . . .
Hopefully this did not prevent you from trying the software?

**Comment by m4r35n357** [comment]
Now fixed

**Comment by keithbriggs** [comment]
Thanks for the fix - I'll try the code tomorrow.

Keith
________________________________
